// <auto-generated />
namespace SaoBei.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class mensalidades1 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(mensalidades1));
        
        string IMigrationMetadata.Id
        {
            get { return "201606221856321_mensalidades1"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
