// <auto-generated />
namespace SaoBei.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Calendario : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Calendario));
        
        string IMigrationMetadata.Id
        {
            get { return "201603071826578_Calendario"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
